export enum RoleEnum {
    CUSTOMER = 'CUSTOMER',
    ADMIN = 'ADMIN',
    PRODUCT_MANAGER = 'PRODUCT_MANAGER',
    ORDER_MANAGER = 'ORDER_MANAGER',
    SUPPORT = 'SUPPORT',
    MARKETING = 'MARKETING',
    LOGISTICS = 'LOGISTICS',
}
